steps:
  # Step 1: Start Selenium Hub and Chrome Node using Docker Compose
  - name: 'docker/compose'
    entrypoint: 'docker-compose'
    args:
      - '-f'
      - 'selenium-hub-docker-compose.yml'
      - 'up'
      - '-d'

  # Step 2: Wait for the Selenium Hub to be ready
  - name: 'docker/compose'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "Waiting for Selenium Hub to be ready..."
        # Wait for a few seconds to allow the services to start
        sleep 10
        # Check if Selenium Hub is up and running
        until $(curl --output /dev/null --silent --head --fail http://localhost:4444/wd/hub); do
          printf '.'
          sleep 5
        done
        echo "Selenium Hub is up!"

  # Step 3: Run Selenium tests with Maven using JDK 17
  - name: 'maven:3.8.5-openjdk-17'
    entrypoint: 'mvn'
    args:
      - 'clean'
      - 'test'

options:
  machineType: 'E2_HIGHCPU_8'  # Optional: Use a more powerful machine if needed
  logging: CLOUD_LOGGING_ONLY
