steps:
# Step 1: Install system dependencies and Chrome
- name: 'docker'
  args: ['run', '-d', '--name', 'browserless', '-p', '3000:3000', 'browserless/chrome']

  # Run Selenium tests with Maven using JDK 17
- name: 'maven:3.8.5-openjdk-17'
  entrypoint: 'mvn'
  args: ['clean', 'test']

options:
  machineType: 'E2_HIGHCPU_8' # Optional: Use a more powerful machine if needed
  logging: CLOUD_LOGGING_ONLY
