steps:
- name: 'ubuntu'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    apt-get update
    apt-get install -y wget gnupg unzip curl
    wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
    echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
    apt-get update
    apt-get install -y google-chrome-stable

  # Run Selenium tests with Maven using JDK 17
- name: 'maven:3.8.5-openjdk-17'
  entrypoint: 'mvn'
  args: ['clean', 'test']

options:
  machineType: 'E2_HIGHCPU_8' # Optional: Use a more powerful machine if needed
  logging: CLOUD_LOGGING_ONLY
