steps:
# Step 1: Install system dependencies and Chrome
- name: 'browserless/chrome'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo "Starting Chrome in headless mode..."

  # Run Selenium tests with Maven using JDK 17
- name: 'maven:3.8.5-openjdk-17'
  entrypoint: 'mvn'
  args: ['clean', 'test']

options:
  machineType: 'E2_HIGHCPU_8' # Optional: Use a more powerful machine if needed
  logging: CLOUD_LOGGING_ONLY
