steps:
- name: 'ubuntu'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    # Update and install dependencies
    apt-get update -y
    apt-get install -y wget gnupg unzip curl

    # Get Chrome version
    CHROME_VERSION=$(google-chrome --version | cut -d ' ' -f 3 | cut -d '.' -f 1)
    echo "Detected Chrome Version: $CHROME_VERSION"

    # Download matching ChromeDriver
    CHROMEDRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION.0)
    echo "Compatible ChromeDriver Version: $CHROMEDRIVER_VERSION"

    # Download ChromeDriver
    wget -N http://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
    unzip chromedriver_linux64.zip
    mv chromedriver /usr/local/bin/chromedriver
    chmod +x /usr/local/bin/chromedriver
    rm chromedriver_linux64.zip

    # List versions to verify
    google-chrome --version
    chromedriver --version

  # Run Selenium tests with Maven using JDK 17
- name: 'maven:3.8.5-openjdk-17'
  entrypoint: 'mvn'
  args: ['clean', 'test']

options:
  machineType: 'E2_HIGHCPU_8' # Optional: Use a more powerful machine if needed
  logging: CLOUD_LOGGING_ONLY
