version: '3'
services:
  selenium-hub:
    image: selenium/hub:4.15.0
    container_name: selenium-hub
    ports:
      - "4442:4442"  # Port for the event bus
      - "4443:4443"  # Port for the event bus publish
      - "4444:4444"  # Port for the Selenium WebDriver

  chrome:
    image: selenium/node-chrome:4.15.0
    shm_size: 2gb  # Increase shared memory for Chrome
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
